[package]
name = "tsunami"
version = "0.11.1"
authors = ["Jon Gjengset <jon@thesquareplanet.com>", "Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"
license = "MIT OR Apache-2.0"

readme = "README.md"
description = "Toolkit for running short-lived jobs on cloud VMs"
repository = "https://github.com/jonhoo/tsunami.git"

keywords = ["orchestration", "cloud", "vm", "ec2", "azure"]
categories = ["api-bindings", "development-tools"]

[badges]
azure-devops = { project = "jonhoo/jonhoo", pipeline = "tsunami", build = "25" }
maintenance = { status = "passively-maintained" }

[features]
default = ["aws", "azure", "baremetal"]
aws = ["rusoto_core", "rusoto_ec2", "futures-util", "tempfile", "ubuntu-ami", "tokio"]
azure = ["serde", "serde_json", "futures-util", "tokio", "tokio/process"]
baremetal = []
args = ["structopt"]

[dependencies]
color-eyre = "0.5"
educe = "0.4"
itertools = "0.10"
openssh = "0.8"
rand = "0.8"
tracing = "0.1"
tracing-futures = "0.2"
rusoto_core = { version = "0.47.0", optional = true }
rusoto_ec2 = { version = "0.47.0", optional = true }
futures-util = { version = "0.3.4", optional = true }
tempfile = { version = "3.0.0", optional = true }
tokio = { version = "1.0.0", features = ["time"], optional = true }
serde_json = { version = "1", optional = true }
serde = { version = "1", features = ["derive"], optional = true}
structopt = { version = "0.3", optional = true }
ubuntu-ami = { version = "0.2", optional = true }

[dev-dependencies]
rusoto_sts = "0.47.0"
tokio = { version = "1.0.0", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = "0.2"

[[example]]
name = "launch"
required-features = ["args"]

[[example]]
name = "ping"
required-features = ["args"]
